[package]
name = "diamond-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.6", features = ["dynamic"] }
bevy-inspector-egui = "0.8"
phf = { version = "0.11", features = ["macros"] }
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
rand = "0.8.5"